version: '3.8'

services:
  keycloak-fapi1-baseline:
    build: .
    ports:
      - '8080:8080'
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-fapi1-baseline-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
    depends_on:
      - keycloak-fapi1-baseline-db
    volumes:
      - keycloak-fapi1-baseline-data:/opt/keycloak/data

  keycloak-fapi1-baseline-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - keycloak-fapi1-baseline-postgres-data:/var/lib/postgresql/data

volumes:
  keycloak-fapi1-baseline-data:
  keycloak-fapi1-baseline-postgres-data:
